### ISSUE TITLE
Automated README.md display does not properly render embedded HTML

### ISSUE THREAD

**Issue by lauratinnel** [ITI/searcch#148]
Look at the README.md file here: https://github.com/icsdataset/hai
Then look at how it is displayed here: https://hub.cyberexperimentation.org/artifact/512

**Comment by carboxylman** [comment]
Closed by @ckouder in PR #164 .

**Comment by carboxylman** [comment]
@ckouder this maybe only half fixes this issue.  See https://hub-dev.cyberexperimentation.org/artifact/475 and compare to github markdown render: https://github.com/icsdataset/hai .  The markdown table isn't rendered, and the HTML table is rendered but seems to lack typical table borders and formatting (maybe because of our style sheet).  Maybe we need a special style sheet for inlined HTML in Markdown?

**Comment by ckouder** [comment]
For the html table: I think the default table in showdown is borderless (see POC) - let me create some styles for it 

For markdown: this is super weird because the table is correctly rendered in POC - I need to dive into the issue

**Comment by carboxylman** [comment]
@ckouder has this fixed as of e3a50bd7 ; tested specifically on this case and working great.
