### ISSUE TITLE
bug: Internal server error while editing user profile

### ISSUE THREAD

**Issue by eeide** [ITI/searcch#41]
**Describe the bug**
On the "Manage Account" page https://hub.cyberexperimentation.org/profile — if I delete the initial empty affiliation, I get an "Internal Server Error" with status code 500.

**To Reproduce**
1. Go to https://hub.cyberexperimentation.org/profile
2. Click on X in the iniial empty affiliation: '( (X))"
3. See error

**Expected behavior**
I expected the widget for the initial empty affiliation to be deleted. (When I did first did this "for real," I entered my affiliation in a second text-entry "bubble." I went to delet th now-unneedd empty bubble, and boom!)

**Screenshots**
<img width="79" alt="Screen Shot 2021-08-16 at 9 36 01 AM" src="https://user-images.githubusercontent.com/160140/129590119-bd688df9-fbf3-450f-a3df-673bb7a18c3c.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Firefox
 - Version: 91.0

**Comment by timyardley** [comment]
@carboxylman let me know if the backend change addresses this, if not, we'll work out a switch to the frontend to ignore it

**Comment by carboxylman** [comment]
Fixed.  I fear the long-term consequences of decoupling the new `UserAffiliation` object completely from `Affiliation`; it does an end-around the data model's object reuse pattern; but that was the only reasonable way forward for now, all things considered.  We could not sanely reuse `Affiliation` as I had hoped (e.g. with a simple UserAffiliation = (User,Affiliation)), because that led to a bug-prone cycle where you would have had this possible foreign key skew ... (UserAffiliation.user,UserAffiliation.affiliation) ; but then given existing User.person and Affiliation.person, it would have been possible for person fkeys to mismatch and create bogus relationships.
