### ISSUE TITLE
Change artifact relationships to support additional and reverse (two-way) relationships

### ISSUE THREAD

**Issue by lauratinnel** [ITI/searcch#46]
Change artifact relationships to support additional and reverse (two-way) relationships. 

Currently supported relationships:
- cites
- supplements
- continues
- references
- documents
- compiles
- publishes

New relationships:
- cites
- cited by
- supplements
- supplemented by
- extends
- extended by
- uses
- used by
- describes
- described by
- requires
- required by
- processes
- processed by
- produces
- produced by

This will allow us to represent the following relationships and enhance usability in that users will be able to get to a related artifact regardless of whether they are viewing the artifact on the left or right side of the relationship.
```
artifact	>	        <	            artifact	Notes

paper	    cites	    cited by	    paper	    General citation of another paper

paper	    extends	    extended by	    paper	    Work described in paper builds on another prior work (stronger citation)

publication supplements supplemented by paper       Detailed technical report or dissertation provides supplemental material for published paper
  
paper	    describes	described by	software	Paper describes an algorithm or function that is implemented in software

paper	    describes	described by	dataset	    Paper describes dataset (can be input or output)

paper	    uses	    used by	        dataset	    Work described in paper uses dataset

paper	    uses	    used by	        software	Work described in paper uses software

software	processes	processed by	dataset	    Software processes an input dataset

software	produces	produced by	    dataset	    Software produces or creates an output dataset

software	requires	required by	    software	Software requires another piece of software to work (may never get used)

```

Required database artifact relationship entry changes are:
- continues -> extends
- references -> cites
- publishes -> uses

This issue focused on the available relationship strings in the system. The implementation of any automated two-way relationships is captured in this issue: https://github.com/ITI/searcch/issues/47

**Comment by carboxylman** [comment]
I haven't thought much beyond my prior comments in slack, but I still think that we don't want to have trivial cycles in the data model itself.  The model does permit cycles; but they have to be explicitly created, and that promotes easier reasoning over the graph, as well as attribution.

The frontend can display both directions if we just give it a little bit more data, and I think that achieves the goal of this issue, so that's how I suggest we address this.

**Comment by lauratinnel** [comment]
My suggestion is that these are explicitly created, but I separated that out into a separate issue because it might take longer to implement.

**Comment by lauratinnel** [comment]
The other question is: should we allow users to create BOTH directions (they could really screw up the model), or do we only let them create one direction and let the system enforce the reverse so we know it's correct?

**Comment by carboxylman** [comment]
Given that the frontend can display both directions seamlessly even if the trivial reverse cycles are not explicit in the model, what is the need for the reverse cycles be explicit in the model?  I don't see any upside; but I see downside (extra tracking for the backend to add/update/delete the reverse direction; cycles that complicate reasoning; inability to attribute who created the relationships).

As far as who creates, only the artifact owner (or admins) can create relationships from her artifact to others.  We do need some kind of control there, and that is the only knob we have at present.  Eventually we could allow users to suggest relationships, and bump the decision to the artifact owner or to admins.  We're set up to do this already because the importer got this notion added to its data model last month, a `CandidateRelationship`; this is what we do so that if the importer sees a possible relationship, it can expose that as a choice to the importing user.  It and the related new objects just haven't been pushed into the backend yet due to time pressure.

**Comment by lauratinnel** [comment]
I was assuming it would be trivial if the importer is handed a relationship to do a table lookup for the reverse and just add that. I was also assuming it would be much more difficult to dynamically generate the reverse relationship in the front end. BUT. I'm not going to prescribe how it is implemented because I don't understand exactly how things are implemented under the covers. I just think we want users to be able to see and walk the relationships in both directions. You and Tim work it out.

**Comment by timyardley** [comment]
new types implemented. you define the forward relationship and the reciprocal is automatically handled for you.

**Comment by timyardley** [comment]
reopen until data migration addresses 
continues -> extends
references -> cites
publishes -> uses

**Comment by carboxylman** [comment]
Question, why are we getting rid of `publishes` ?  That seems to me a reasonable relation whose meaning is more specific than `uses` and relevant to the community.  I agree with adding `uses` so that we cover some extra cases, and we had agreed to that in a previous team meeting, and it is in the importer (just didn't make it to backend I think).

**Comment by lauratinnel** [comment]
Give me an example of an artifact that actually publishes another artifact. Software doesn't publish data. Papers don't publish software. An author publishes something. A conference publishes something. Authors and conferences are not artifacts. And worse, a publishes relationship is confusing when we have a primary artifact type "publication".

**Comment by lauratinnel** [comment]
We could get rid of "uses" and just use "describes". A publication describes software and datasets. We already have "describes" so "uses" may be redundant.

**Comment by carboxylman** [comment]
I agree that those are examples of "publish", yes, but the definition is as broad as publicly announcing something, and that is my use case here.  Some pubs use or reuse software (esp follow-on or competitor/peer works, so either "use" or "extend" there); some pubs announce it, originate it, describe it; they are the root.  The root is the relationship I was trying not to lose in a publish -> uses transformation; hence my acceptance of the "publicly announce" definition of "publish" for this use case.  Describe is not quite originate but seems close enough :)

What if we do the migration with a publishes -> describes transformation?  I suspect that is correct for all the existing content...

(FWIW, I think "uses" is good to keep because it gives people an escape hatch if a more specific relation doesn't work.)

**Comment by lauratinnel** [comment]
OK. Sure. That seems reasonable.
