### ISSUE TITLE
Make github permissions explicit during account creation (Source: BETA Test)

### ISSUE THREAD

**Issue by lauratinnel** [ITI/searcch#92]
Thinks it would be better to explain Github permission rules during account creation rather that in the FAQ. People will likely just go to account creation without reading the FAQ.

**Comment by dpemmerich** [comment]
Maybe I am misunderstanding this. on https://hub.cyberexperimentation.org, if I click the "Github Login" button, it directs me straight to https://github.com login page. From that page, I can either login with my github account or create a github account. Since that page is actually owned by github, we cannot edit that page. So, we either don't do this, or we need our own login page that allows us to explain the use of github accounts.

**Comment by carboxylman** [comment]
I think the only piece we can change is to preface the `Github Login` button in our interface with details; or to change the descriptor text of our Github SSO "App" -- the piece that contains the SEARCCH logo.  Not sure how long the description can be for that.

But also note that Github already explains the permissions you are granting to the SEARCCH app when you click "Authorize", so I'm not sure if anything needs to be done here.

**Comment by dpemmerich** [comment]
There doesn't seem to be much we can change on the github login page directly in the github application settings.

![image](https://user-images.githubusercontent.com/23170883/146841184-0a72e94d-e38e-46cc-86bd-8c49f0618dbf.png)
