### ISSUE TITLE
Importer creates duplicate keywords for DOIs

### ISSUE THREAD

**Issue by lauratinnel** [ITI/searcch#96]
**Describe the bug**
When importing from a DOI, the importer creates/suggests duplicate keywords with different cases (e.g., "Test" and "test"). 

**To Reproduce**
1. From the SEARCCH importer, import "https://dl.acm.org/doi/pdf/10.1145/3474718.3474726"
2. Click on Edit
3. Look at the keywords extracted

**Expected behavior**
Importer should filter keywords using a case insensitive filter. 

**Screenshots**
<img width="1102" alt="Screen Shot 2021-10-13 at 7 21 42 AM" src="https://user-images.githubusercontent.com/3372750/137123478-e2a5ea0b-8194-469b-845f-d7cc0249a303.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 93.0 64-bit

**Smartphone (please complete the following information):**
 n/a

**Additional context**

**Comment by lauratinnel** [comment]
Actually, it's creating duplicates even with the same case.

**Comment by carboxylman** [comment]
Yes, believe it or not, that was intentional, but it is far too overwhelming to remove all the duplicates.  We are already storing the exact kw/rank info as metadata, so we don't need to promote duplicates.  Fixed in https://gitlab.flux.utah.edu/searcch/importer/-/commit/72d442b643a1c6cb7dd449fdb5a92f69aec0247a ; no duplicates are allowed; first case wins.
